### PR TITLE
speed up the build_input function

### PR DESCRIPTION
**Pull request by chenxinfeng4**
1. Create the "triangulate_all_pairs_fast" as an alternative of "triangulate_all_pairs". The "triangulate_all_pairs_fast" use numpy array and cv2 to calculate all the samples.
2. Revised the 'build_input'.

The orignal 'build_input' for 20k 3D points reconstraction will take 10+hours, now **it's 3min.**

### CODE REVIEW

**Comment by lcit** [comment]
The argument each is not handled properly. It crashes when each !=1.

**Comment by chenxinfeng4** [comment]
I will check

**Comment by chenxinfeng4** [comment]
I've fix this bug in last pull. Check whether it works for you?

**Comment by lcit** [comment]
Sorry for the late reply. It works great now, thanks.

**Pull request merged**
